---
- name: verify uv installation
  command: "{{ uv_install_dir }}/uv --version"
  register: uv_version_check
  changed_when: false
  failed_when: uv_version not in uv_version_check.stdout

- name: verify uvx installation
  command: "{{ uv_install_dir }}/uvx --version"
  register: uvx_version_check
  changed_when: false
  failed_when: uv_version not in uvx_version_check.stdout