---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-role-uv
